### PR TITLE
Remove IntelliJ IDEA specific directory and files

### PR DESCRIPTION
**Pull request by bazzani**
IntelliJ IDEA specific files are being tracked by git, but they are
mostly relating to a users local development environment, and therefore
they should not be tracked.

This commit makes two main changes:

1. Add IntelliJ IDEA directory/files to .gitignore
1. Remove IDEA specific directory and files

**Add IntelliJ IDEA directory/files to .gitignore**
Some IDE-specific files are not being ignored, which makes the local
working directory busier than it needs to be.

The .idea directory, .ipr and .iws files have been added to the
gitignore list to make working with your local git repository easier, as
there are not as many untracked files after importing the project to
IDEA.

**Remove IDEA specific directory and files**
The files under the .idea/ directory and the *.iml/*.eml files have been
deleted, as they relate to a users local development environment.

### CODE REVIEW

**Comment by bazzani** [comment]
Hi @nikhilnanivadekar,

I have removed and ignored all IDEA specific files, but there are a few things I noticed when doing so that I would like to bring to your attention.

1. **.name** file in _.idea_ directory
1. copyright files in _.idea/copyright_ directory
1. IDEA compiler Error after import

### **.name** file in _.idea_ directory
After removing this file, does it warrant a change in the top level pom file, so that that top level project will have the name _eclipse-collections-kata_?
- from `<artifactId>eclipse-collections-kata-parent</artifactId>`
- to `<artifactId>eclipse-collections-kata</artifactId>`

### copyright files in _.idea/copyright_ directory
Is the `.idea/copyright/Eclipse.xml` needed, and should it be in the .`idea` directory?
Eclipse.xml contents:
```
$ cat .idea/copyright/Eclipse.xml
<component name="CopyrightManager">
  <copyright>
    <option name="notice" value="Copyright (c) &amp;#36;today.year Goldman Sachs.&#10;All rights reserved. This program and the accompanying materials&#10;are made available under the terms of the Eclipse Public License v1.0&#10;and Eclipse Distribution License v. 1.0 which accompany this distribution.&#10;The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html&#10;and the Eclipse Distribution License is available at&#10;http://www.eclipse.org/org/documents/edl-v10.php." />
    <option name="keyword" value="Copyright" />
    <option name="allowReplaceKeyword" value="Goldman Sachs" />
    <option name="myName" value="Eclipse" />
    <option name="myLocal" value="true" />
  </copyright>
</component>
```

###  IDEA compiler Error after import
After removing all IDEA specific files and initialising the project with gradle (`$ ./gradlew idea`), I got an error popup dialog when I first tried to compile the projects (Ctrl+F9) in IDEA, snag attached:
image

This is easily resolved by selecting the correct JDK version (8 in my case) from the _Project Structure_ dialog window (snags below), which updates the (now removed/ignored) `.idea/compiler.xml` file.

Should I update the README with an FAQ section to show this potential problem?

image

image

**Comment by motlin** [comment]
We had a similar conversation here:
https://github.com/eclipse/eclipse-collections/issues/581

Some IntelliJ project files are designed to be committed and some must be
excluded. We’ve gotten out of sync and appreciate pull requests that get us
back in sync. We don’t want to just delete .idea/ completely. The copyright
confirm you found is one example that helps us contributors.

**Comment by nikhilnanivadekar** [comment]
Is there anything other than copyright that is needed? I think all other files which Barry has deleted are unnecessary. We will not be running TC builds for the kata, and in versions of IntelliJ the kata opens up without these files.

**Comment by motlin** [comment]
It’s probably good to delete .idea/libraries/

It may be beneficial to delete misc.xml but I’m not sure.

There is one file ending in eml instead of iml. Is that a mistake?

I’m not sure if IntellJ’s gradle plugin has the auto import feature that
the maven plugin has. If so, we could also delete modules.xml.

We should keep the rest. This comes up like once per year so I wouldn’t
mind adding something to contributing.md about which files do what.

**Comment by nikhilnanivadekar** [comment]
eml is most likely for eclipse. I say we just delete them and add as required

**Comment by bazzani** [comment]
Thanks for the input @nikhilnanivadekar and @motlin.
What I can tell you from my recent tinkerings is that I can generate the IDE specific files using `./gradlew idea` and then open the project by following the README [instructions](https://github.com/eclipse/eclipse-collections-kata/#intellij-idea-users).  The only manual step is to select the SDK to compile the project with.

This standard of only committing maven/gradle project files is something I have seen on several projects in recent years, both private and open source.

Indeed, most of these files were originally added in this commit 3862c035adf6685c29f277c43c1391ef783cdc31 back in 02/2016.

Having read this [blog post](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems) from JetBrains (which was updated only yesterday), they recommend the following approach:
> You may consider not to share the following:
> - **.iml** files and **.idea/modules.xml** file for the Gradle or Maven based projects, since these files will be generated on import
> - **gradle.xml** file, see this discussion
> - user **dictionaries** folder (to avoid conflicts if other developer has the same name)
> - XML files under **.idea/libraries** in case they are generated from Gradle or Maven project

I will take another stab at removing/ignoring only the files on the above list and let you know when I have pushed the new commit.

**Comment by bazzani** [comment]
@motlin 
> I’m not sure if IntellJ’s gradle plugin has the auto import feature that
> the maven plugin has. If so, we could also delete modules.xml.

Just an FYI that I opened the project in IDEA after running the `./gradlew idea` command, and then imported both the maven project, and then tried again from scratch importing the gradle project.  Both worked without any issues.

In fact, importing the gradle project did not require the manual step of select the SDK to compile with that maven required me to do after importing.  Gradle seems to be more intelligent than maven 👍

**Comment by nikhilnanivadekar** [comment]
IntelliJ should auto-create the modules.xml file

**Comment by bazzani** [comment]
@nikhilnanivadekar / @motlin I would like to close this PR, and replace it with the new #68, which has a more suitable commit message and change set.
Can you please have a look at #68 when you get a chance?

**Pull request closed without merging**
