### PR TITLE
Removing gradle build set up as the project is already set up for maven.

### PR DESCRIPTION
**Pull request by prathasirisha**
Tested the changes to import projects to both Intellij IDE and Eclipse IDE.

### CODE REVIEW

**Comment by motlin** [comment]
One reason we added gradle was to make the kata self contained. At the time, gradle supported wrappers and maven didn't. Now maven supports wrappers, through the takari plugin, so I'd suggest adding those in the same PR.

**Comment by nikhilnanivadekar** [comment]
I don’t think the wrappers are necessary at all. I guess they’ll be necessary when a user does not have a modern IDE with built in maven support. But from my experience all 3- IntelliJ, Eclipse and Netbeans just work without any issues whatsoever. A user has to download and open the project and it’s all setup. I don’t quite follow the role maven wrapper will play in this case. May be I am missing something, can you please elaborate?

**Comment by motlin** [comment]
It makes the kata self contained. You can do the kata with vim/emacs and
just run the wrapper. It's more inclusive of us to support multiple IDEs
and multiple builds, or at least one self-contained build.

**Comment by nikhilnanivadekar** [comment]
I don’t mind adding a maven wrapper, but supporting vim/emacs is a bit of a stretch. Without the wrapper it works for IDEs. I’ll be happy to take the changes for including a wrapper.

**Comment by nikhilnanivadekar** [comment]
Only 1 comment to fix. Please rebase on to master and I will merge. Thank you!

**Comment by prathasirisha** [comment]
rebased, please check now.

**Comment by itohiro73** [comment]
Hi, sorry to jump in late. 

The other reason why we added gradle is just so that people can choose the build they like. What's the problem with keeping both?

I agree with Craig's comment below.
> It's more inclusive of us to support multiple IDEs and multiple builds

**Comment by nikhilnanivadekar** [comment]
The problem is consistency of experience. Don’t quite still understand the reasoning behind having both. Even if there was gradle wrapper still after the build is setup all instructions are for a maven build. I have conducted the kata numerous times with a consistent feedback that the gradle instructions are confusing and superfluous.

**Comment by donraab** [comment]
My experience with the Gradle build wrapper has been the same as @nikhilnanivadekar.  I recall and understand the original intent, but to date I have seen it provide near zero value.

**Pull request merged**
