### PR TITLE
Initial import of the Eclipse Collections Kata.

### PR DESCRIPTION
**Pull request by motlin**
Builds on top of #1. Adds configuration of maven, gradle, Eclipse, and IntelliJ and migrates the sources from the GS Collections Kata.

### CODE REVIEW

**Comment by itohro** [comment]
Thanks, this looks good to me overall besides the extra backquote mentioned above.

Could you please separate a commit for company kata and submit it in a separate pull request?

Pet Kata is originated from the source code that has been already reviewed and approved by Eclipse IP team, so it's fine to be merged right away. We can start putting together solutions and slides for Pet kata.

Company Kata (i.e. GS Collections Kata) sources code haven't been reviewed by Eclipse IP team yet. We need to raise a CQ and get them reviewed and approved. It might take some time depending on their work queue.

**Comment by motlin** [comment]
Thanks. I fixed the compilation error you pointed out. I'll have to work on Travis builds soon to prevent that kind of problem in the future.

I split the final commit into two, one for each set of exercises. Only the final commit b858b17a3387decedca6db0030f36cab6e4d5bce should need review.

**Comment by itohro** [comment]
Thank you, yes Travis build would be beneficial here. 

Thanks for splitting the commit (I think you meant 529e4ec, not b858b17). Would you mind putting 529e4ec (company kata) in a separate branch and submit it as a separate pull-request? 

I'd want to merge Pet Kata for now.

**Comment by motlin** [comment]
Done. Removed the final commit from this pull request and create a separate branch for it at https://github.com/motlin/eclipse-collections-kata/commits/mini-kata. So both links in your comment still work.

**Comment by itohro** [comment]
LGTM :+1:

**Pull request merged**
