### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by harshavardhi123**

### CODE REVIEW

**Comment by Sweta716** [comment]
Amend the commit statement to the standard
Fix #issuenumber and what did you do?

**Comment by harshavardhi123** [comment]
Done the changes to my commit message

**Comment by prathasirisha** [comment]
@harshavardhi123 please pull the latest changes in and rebase on master. To achieve this, you can run the following two commands - 

git pull --rebase upstream master 
git push --force-with-lease

**Review by Sweta716 — APPROVED** [review]

**Comment by prathasirisha** [comment]
Please amend the commit message like so - 

git commit --amend -m "Remove unused imports. Closes #307" 
git push --force-with-lease

**Comment by prathasirisha** [comment]
Thank you for your contribution @harshavardhi123!

**Pull request merged**
