### PR TITLE
Corrected minor typo.

### PR DESCRIPTION
**Pull request by haasted**
Fixed a minor typo in a test name.

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
@haasted thank you for the PR. Can you please complete the IP validation?
You can follow the How to Contribute guide from Eclipse Collections: https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md

**Comment by haasted** [comment]
I completed the IP validation. :)

**Comment by nikhilnanivadekar** [comment]
@haasted looks good. Thanks! I would suggest removing the 
> Now signed off.
part from the commit message. Once fixed it is good to be merged. 
Thanks!

**Comment by haasted** [comment]
All right.

**Pull request merged**
